version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5001:5000"
    volumes:
      - .:/vidly
      - /vidly/node_modules # Prevents host from overwriting container's node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    stdin_open: true # Keep STDIN open for interactive development
    tty: true # Allocate a pseudo-TTY
    restart: unless-stopped
